### ISSUE TITLE
Improper Dependency Scope Attribution

### ISSUE THREAD

**Issue by alzimmermsft** [JonathanGiles/DependencyChecker#7]
https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-java/staging/pom.client.html

It appears that dependencies of test dependencies are being improperly attributed as compile/runtime dependencies. In the output above `azure-storage-blob-cryptography` is listing a `2.9.9` dependency on `jackson-annotations`. `azure-storage-blob-cryptography` doesn't list `jackson-annotations` as a compile/runtime dependency, it appears this is a dependency in its test dependency on `azure-keyvault-cryptography`.

**Comment by JonathanGiles** [comment]
Resolved in 1.0.4.
